### ISSUE TITLE
Proxy test: accept IP address from UI and replace in etc/hosts file

### ISSUE THREAD

**Issue by uzfarid** [k8-proxy/aws-jmeter-test-engine#200]
127.0.0.1 www.gov.uk.local assets.publishing.service.gov.uk.local www.gov.uk assets.publishing.service.gov.uk.glasswall-icap.com

basically in hosts file we replace 127.0.0.1 with passed IP address. 

in UI when load type is selected, it should ask for Proxy End IP IP address.

**Comment by jpoolGW** [comment]
Can mark this as done, but task needs to be created to update the values passed
