### ISSUE TITLE
Create heart beat load test using the defined base load script on test plan

### ISSUE THREAD

**Issue by NadHodeGW** [k8-proxy/aws-jmeter-test-engine#21]
Create heart beat load test using the defined base load script on test plan.
Continuous running test separately monitored via live dashboard

**Comment by uzfarid** [comment]
@NadHodeGW how this heart beat load test should be triggered? is there some Jenkins or Bamboo? or should it be , for example scheduled to run via AWS Lambda functions? i.e lambda function can be scheduled to trigger load generators, let's say, everyday for 30 mins, at 6am.
