### ISSUE TITLE
Optimize usage of S3 while load is running

### ISSUE THREAD

**Issue by NadHodeGW** [k8-proxy/aws-jmeter-test-engine#23]
Optimize usage of S3 while load is running to reduce load on load generator machine itself while out files are copied to s3

**Comment by uzfarid** [comment]
https://github.com/k8-proxy/aws-jmeter-test-engine-v1/pull/25 managed to find new way to handle S3 upload of out files.

**Comment by uzfarid** [comment]
next step is to integrate with mains script and verify performance

**Comment by uzfarid** [comment]
next step is to move in part to java code

**Comment by uzfarid** [comment]
in part is also now java code, we dont have any more s3 cli running in background. this should reduce resource usage.
