### ISSUE TITLE
Enhance SharePoint API Key Generation and Permissions documentation

### ISSUE THREAD

**Issue by michaelhidalgo** [k8-proxy/aws-jmeter-test-engine#270]
First, of all, this is a great guide https://github.com/k8-proxy/aws-jmeter-test-engine/blob/sharepoint-fixes/jmeter-icap/instructions/How-to-Generate-Load-against-Proxied-SharePoint.md . 

It would be good to document a bit more the permissions that are required by the Application ID generated and the scopes it requires documenting the XML for the app-only. [Please follow this guide](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs).

It seems like this Application just needs Read, Write rights on the target folder so the scope should be limited to that resource. 

Please check out this documentation about permissions:
+ https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-in-permissions-in-sharepoint
+ https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs

Also, as per the documentation, to add two different permissions, two AppPermissionRequest Scope are needed

```
<AppPermissionRequests AllowAppOnlyPolicy="true">
  <AppPermissionRequest Scope="http://sharepoint/content/tenant" Right="Read" />
<AppPermissionRequest Scope="http://sharepoint/content/tenant" Right="Write" />
</AppPermissionRequests>
```

Also, it would be interesting to narrow down the Scope required:

- Tenancy: The tenancy where the add-in is installed. Includes all children of this scope.
- Site Collection: The site collection where the add-in is installed. Includes all children of this scope
- Website: The website where the add-in is installed. Includes all children of this scope
- List: A single list in the website where the add-in is installed.

When the user who installs the add-in is prompted to grant permissions, the dialog enables the user to select one list to which the add-in is granted permissions.

**Comment by uzfarid** [comment]
@michaelhidalgo thanks for suggestions.I would not want to make guidelines to be more about Sharepoint. it is up to end user to ensure that proper rights are given. if majority part of the guideline becomes about Sharepoint itself then main focus of the guideline would be lost.
However, I can add those links, so that end user who is creating those keys should consider those.

**Comment by uzfarid** [comment]
https://github.com/k8-proxy/aws-jmeter-test-engine/blob/master/jmeter-icap/instructions/How-to-Generate-Load-against-Proxied-SharePoint.md now documentation updated

**Comment by michaelhidalgo** [comment]
Thanks, @uzfarid, Yeah I agree the purpose of the docs should not be focused on just SharePoint but our posture should be secure by default, that is that we run stuff with the Least Privilege Principle. So one paragraph or two about this gives the sense that we care about our customer's security.

**Comment by uzfarid** [comment]
@michaelhidalgo I added some stuff, and also showed what exactly is needed for permissions, is it enough or something else should be added?

**Comment by michaelhidalgo** [comment]
Yeah I think we are good, thanks  @uzfarid
