### ISSUE TITLE
Change URL in Documentation 

### ISSUE THREAD

**Issue by svf97** [k8-proxy/aws-jmeter-test-engine#281]
For the documentation: https://github.com/k8-proxy/aws-jmeter-test-engine/blob/master/jmeter-icap/instructions/How-to-generate-Scaled-Load-via-UI.md
Please change the "main instructions" URL should point to https://github.com/k8-proxy/aws-jmeter-test-engine/blob/master/README.md instead of https://github.com/k8-proxy/aws-jmeter-test-engine/README.MD

**Comment by uzfarid** [comment]
thanks these are fixed now
