### ISSUE TITLE
Create release 

### ISSUE THREAD

**Issue by uzfarid** [k8-proxy/aws-jmeter-test-engine#289]
Create v0.2.0 Release notes:

- Implemented UI interface to be able to trigger load
- UI Interface supports load agains direct icap, via proxy offline site and proxied Sharepoint
- Implemented to stop tests from UI
- Implemented performance test summary results table in UI
- ICAPServer Performance Test and Analytics Ubuntu AMI is published in all supported regions
- Implemented results automatic analyser. 
- Both dashboard and load generators are now based on Ubuntu 20.04

**Comment by shashanksinha89** [comment]
release link : https://github.com/k8-proxy/aws-jmeter-test-engine/releases/tag/v0.2.0
