### ISSUE TITLE
Building Grafana graphs based on ICAP Server metrics and integrate those graphs to main grafana dashboard template

### ISSUE THREAD

**Issue by jpoolGW** [k8-proxy/aws-jmeter-test-engine#30]

**Comment by hongson1981** [comment]
I am working on this issue via link below 
https://github.com/k8-proxy/p-k8-jmeter-test-engine/issues/15
Please do not assign to other to avoid duplicated

**Comment by uzfarid** [comment]
@hongson1981 please explain ur approach to this.

**Comment by hongson1981** [comment]
@uzfarid 
My solution :
First, Create JRS223 PreProcesser to : 
1. Run command "/usr/local/c-icap/bin/c-icap-client -s info?view=text -i gw-icap01.westeurope.azurecontainer.io -req any" to get ICAP server metrics
2. Convert ICAP server metrics from text to  InfluxDB line protocol syntax like this  
   Running Servers Statistics 20201007184538 ....
   General Statistics Children number=3,Free Servers=26,Used Servers=4  ...
   Service info Statistics REQUESTS=705,REQMODS=6, ....
   Service echo Statistics Service info REQMODS=6,Service info RESPMODS=0,....
   Service gw_rebuild Statistics Service echo REQMODS=0,Service echo RESPMODS=0,..
each line is one measurement
3. Put all measurements to variable ${icap_measurements}
Second, Create http sampler to post  ${icap_measurements} to influxDB server
Third, Using Grafana to present icap_measurement on Dashboard
Currently, I am working on .2 Convert ICAP server metrics from text to  InfluxDB line protocol syntax,

**Comment by uzfarid** [comment]
in this case, we can re-use what @hongson1981 created in k8-jmeter-test-engine project

**Comment by uzfarid** [comment]
Next target is to build grafana dashboard with these icap server metrics.
