### ISSUE TITLE
6: Cannot copy full gov-uk content to S3 on WIN

### ISSUE THREAD

**Issue by MaNe2020** [k8-proxy/aws-jmeter-test-engine#309]
Content cannot be copied, nor via drag'n'drop, nor via direct folder upload, nor via aws cli.
This is noticed just on win based system.
And it is familiar issue as win has limitation for file path length to 255.

Whole process should be automated in order to avoid system dependencies.

**Comment by uzfarid** [comment]
https://github.com/k8-proxy/aws-jmeter-test-engine/issues/308 this will get resolved in here
