### ISSUE TITLE
Add error % metric to performance dashboards

### ISSUE THREAD

**Issue by uzfarid** [k8-proxy/aws-jmeter-test-engine#334]

**Comment by ggrig** [comment]
Looks like we'll need MetaQueries installed in the Grafana for this
https://grafana.com/grafana/plugins/goshposh-metaqueries-datasource

**Comment by ggrig** [comment]
More details at https://community.grafana.com/t/how-to-divide-querya-value-by-query-b-value-and-graph-result/13612

**Comment by ggrig** [comment]
Meta queries may have issues with latest Grafana releases
https://github.com/GoshPosh/grafana-meta-queries/issues/104
