### ISSUE TITLE
Cannot login with 'glasswall' user to the recent OVA

### ISSUE THREAD

**Issue by ggrig** [k8-proxy/aws-jmeter-test-engine#423]
The issue has been discovered with

https://s3.console.aws.amazon.com/s3/object/ova-creation?region=eu-west-1&prefix=vms/export-i-0a00e2083c0c4f922.ova

**Comment by shashanksinha89** [comment]
reference ova: https://ova-creation.s3-eu-west-1.amazonaws.com/vms/export-i-060db26295300d268.ova
