### ISSUE TITLE
Grafana dashboard is still missing some file types

### ISSUE THREAD

**Issue by jpoolGW** [k8-proxy/aws-jmeter-test-engine#440]
I have added some of the missing file types to the success response time graph in this file
s3://aws-testengine-s3/**Grafana json files/updated-json-dashboard.json

- jpg
- png
- tif

There may still be some missing types such as tiff

We can use this file to update the existing ones. But we also need to go through the file types in the csv files and ensure all types are added to success and failure response time graphs

**Comment by uzfarid** [comment]
this can be closed now as we moved into file names instead of types.
