### ISSUE TITLE
Create automation to create datasource automatically.

### ISSUE THREAD

**Issue by uzfarid** [k8-proxy/aws-jmeter-test-engine#451]
script should accept datasource name and datasource url as parameter

**Comment by uzfarid** [comment]
https://github.com/k8-proxy/aws-jmeter-test-engine/blob/master/jmeter-icap/scripts/create_datasource.py

**Comment by uzfarid** [comment]
do not make it as part of deployment automation.

**Comment by himanshu2464** [comment]
this is done here is the PR.
https://github.com/k8-proxy/aws-jmeter-test-engine/pull/461
