### ISSUE TITLE
Implement the ability to create a dashboard for a single stack

### ISSUE THREAD

**Issue by NadHodeGW** [k8-proxy/aws-jmeter-test-engine#50]
Problems this will solve
1-Currently it's difficult to run tests straight after one has completed as it takes a while for the metrics to clear up
2- It's confusing to know what metrics a test run a has returns and when exactly it has completed when a test run b has been started as well

**Comment by uzfarid** [comment]
dashboard stuff will be assigned to new guys just joined in.

**Comment by uzfarid** [comment]
main thing is capability to pass prefix to create dashboard script. 

python createDashboard.py -f dashboard template.json - prefix prefixName
