### ISSUE TITLE
See if there is a way to fetch AWS credentials from GitHub Secrets

### ISSUE THREAD

**Issue by jpoolGW** [k8-proxy/aws-jmeter-test-engine#52]
Once we have new AWS credentials we want to see if our EC2 instance can fetch values from GitHub Secrets.
Then we can store the AWS credentials in GitHub secrets. If there are changes to these we can simply update the Git Repo

**Comment by shashanksinha89** [comment]
@jpoolGW @uzfarid : Here are the steps.

Using `aws-secret-manager` with EC2 instance (via IAM role) to allow fetching specific secret.

- Create below IAM policy

```
{
    "Version": "2012-10-17",
    "Statement": {
        "Effect": "Allow",
        "Action": "secretsmanager:GetSecretValue",
        "Resource": "<arn-of-the-secret-the-app-needs-to-access>"
    }
}

```

- Create `IAM ROLE`  and select `Allows EC2 instances to call AWS services on your behalf.`

- Attach above IAM role to EC2 instance which needs to access the secret

- Once attached, run bellow command from cli (considering aws-cli is present)

```
aws secretsmanager get-secret-value --secret-id <secret_name> --region eu-west-1
```
- Output can be manipulated to store it in `ENV_VAR` if required.


<img width="881" alt="Screen Shot 2020-10-20 at 1 50 36 PM" src="https://user-images.githubusercontent.com/13620565/96570492-7ed5a300-12db-11eb-973b-f272dc1a1b3e.png">

**Comment by jpoolGW** [comment]
I have updated the StartExecution.sh script to make a call to secrets manager and fetch the AWS Credentials from there. I have created the IAM Role needed to access Secrets Manager and S3.
We will need a task to attach the IAM Role to the EC2 instances started by the cloudformation script

**Comment by shashanksinha89** [comment]
#63
