### ISSUE TITLE
Modify Jmeter to send different error codes to influx DB to show on the dashboard

### ISSUE THREAD

**Issue by uzfarid** [k8-proxy/aws-jmeter-test-engine#54]
Error code:

204, 503, 500, 400

**Comment by hongson1981** [comment]
@uzfarid 
Update status of this issue :
Almost done, I will create README.md and PR tomorrow,
All codes are temporary pushed on my git https://github.com/hongson1981/aws-jmeter-test-engine-v1/tree/master/upwork-devs/Son-Ha
