### ISSUE TITLE
Build capability to handle zip files in Jmeter script

### ISSUE THREAD

**Issue by uzfarid** [k8-proxy/aws-jmeter-test-engine#60]
test-data team providing virus test files and they are zipped files.

file structure is the following:

zip file contains:
      original virus file as zip

basically it is zip inside zip. reason behind this is security.  jmeter script needs to do unzipping twice, and send original file to icap server and verify it's hash.

once virus file is pushed to icap server and rebuild file is generated, we need to remove original virus file from local file system.

we will run this script separately from other scenarios due to it being scenario only for virus files.

**Comment by uzfarid** [comment]
@MaNe2020 what is status of this one?

**Comment by MaNe2020** [comment]
@uzfarid PR will be created by tomorrow.

**Comment by MaNe2020** [comment]
@uzfarid few questions:

- is this file going to have zip and inside that zip just another zip with malware file? No other files there?
- will zip and inside zip going to continue to have same name? (this would be great if possible)
- at the moment zip and inside zip have the same name but malware file has some common generic one.. if that is going to be case, we should make sure that we have csv with zip file names at least.. it would be also great if we can have malware file also in the csv, just checking
- as we are going to have separate test run for this, current script will unzip one by one file, do we want them to be deleted right afterwards or to have tearDown thread group that will delete all at once?

**Comment by uzfarid** [comment]
@MaNe2020 
- yes, 2nd unzip will need password to unzip.
-I think it is like that I will check
- yes we will have csv with file path, file size, original hash and rebuild hash
- I think best to delete as soon as it is processed. otherwise if test runs longer then disk might get full
